name: Check Sites

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  check_sites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Run site checks
        run: python check_sites.py

      - name: Commit status.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add status.json
          git commit -m "Update site status [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
