name: Website Monitor

on:
  # Schedule to run every 5 minutes
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This grants write access to the repository contents
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9" # Or your preferred Python version (e.g., '3.10', '3.11')

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run site check script
        run: python check_sites.py

      - name: Commit and push status.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add status.json
          git commit -m "Update status.json" || echo "No changes to commit"
          git push
